name: Build and Upload ISO

on:
  push:
    tags:
      - 'rocky-*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Get latest Rocky Linux tag
      id: get_tag
      run: |
        git fetch --tags
        latest_tag=$(git tag --list 'rocky-*' | sort -V | tail -n1)
        echo "LATEST_TAG=$latest_tag" >> $GITHUB_ENV
        echo "ROCKY_VERSION=${latest_tag#rocky-}" >> $GITHUB_ENV

    - name: Download Rocky Linux ISO
      run: |
        wget -nv -O rocky.iso https://download.rockylinux.org/pub/rocky/${ROCKY_VERSION}/isos/x86_64/Rocky-${ROCKY_VERSION}-x86_64-minimal.iso

    - name: Build container
      run: |
        buildah build -t ns8-boxbuilder .

    - name: Create modified ISO
      run: |
        podman run --rm -it --privileged -v $(pwd):/root localhost/ns8-boxbuilder mkksiso -R "Rocky Linux" "NethServer 8 (Rocky Linux)" --cmdline "inst.ks=https://raw.githubusercontent.com/NethServer/ns8-rocky-iso/refs/heads/main/ks.cfg" rocky.iso ns8-rocky-${ROCKY_VERSION}-x86_64.iso

    - name: Create GitHub Release and Upload ISO
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.LATEST_TAG }}
        name: Rocky Linux ${{ env.ROCKY_VERSION }} for NethServer 8
        files: ns8-rocky-${{ env.ROCKY_VERSION }}-x86_64.iso
